@startuml
Користувач->ПрацівникСП : Створює тікет з проблемою
note right: Можливо EX_01
ПрацівникСП->Користувач: Працівник СП дає відповідь на поставлене питання або вирішує проблему.
ПрацівникСП->Користувач: Закриває тікет
@enduml
