@startuml
Користувач->ПрацівникСП : Висловлює бажає видалити аккаунт
ПрацівникСП->Адміністратор : Передає бажання користувача адміністратору
note right: Можливо EX_01
Адміністратор->Користувач : Аккаунт видаляєтся
@enduml
