@startuml
Адміністратор->Система : Переходить в панель адміністратора
Адміністратор->Система : Вписує логін аккаунта в якого хоче забрати права
note right: Можливо EX_01
Система->Користувач: Забирає права у вказаного аккаунту
note right: Можливо EX_02
@enduml
