@startuml
Адміністратор->Система : Переходить в панель адміністратора
Адміністратор->Система : Вписує логін аккаунта якому хоче видати права
note right: Можливо EX_01
Система->Користувач : Видає права вказаному аккаунту
note right: Можливо EX_02
@enduml
