@startuml
Користувач->ПрацівникСП : Створює тікет з проблемою
ПрацівникСП->Користувач: Працівник СП не дає відповідь на поставлене питання або не вирішує проблему.
ПрацівникСП->Адміністоратор: Працівник СП просить допомоги у адміністратора.
Адміністоратор->ПрацівникСП: Дає відповідь на запитання або вирішує проблему
note right: Можливо EX_01
ПрацівникСП->Користувач: Передає виріщення проблеми користвувачу
ПрацівникСП->Користувач: Закриває тікет
@enduml
