@startuml
Користувач->Система : Натискає на кнопку відновлення паролю
Система->Користувач : Видає форму для вводу логіну
note right: Можливо EX_01
Система->Користувач : Відправляє посилання для відновлення паролю на вказаний при регистрації email
Користувач->Система : Переходить по посиланню
Користувач->Система : Вводить новий пароль
note left: Можливо EX_02
Система->Користувач : Встановлює новий пароль
@enduml
