@startuml
Користувач->Система : Натискає на перегляд статистики розвитку України
Система->Користувач : Робить запит до БД
note right: Можливо EX_01
Система->Користувач : Отримує данні 
Система->Користувач : Будує графіки
Система->Користувач : Видає статистику та графіки користувачу
@enduml
